/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ff674377-edb4-4fe3-bedd-2b87092b1f97",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_jg8WdunOS",
    "aws_user_pools_web_client_id": "lo3f2oceiav8dcs1ts4juio9p",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://tpqaxasj6vaj3iyx5gm6caa5wu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2qix5wk2f5aq7hblt7n2hbgp24",
    "aws_cloud_logic_custom": [
        {
            "name": "myGymRestApi",
            "endpoint": "https://ws2u5u7ouj.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ]
};


module.exports = awsmobile;
