/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://zkxcpixjvjhkheennf5wndy63e.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5vpnkvlutrbi5coocynqb6m4iu",
    "aws_cognito_identity_pool_id": "us-east-2:4caa6247-e99c-4b8c-81ed-3902430caeda",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_sQZyRCAxa",
    "aws_user_pools_web_client_id": "5tu8chtrctuhg8hfut41tih2v",
    "oauth": {}
};


export default awsmobile;
